version: '3.1'

services:
    api_vosk:
        image: python:3.11
        container_name: API-Vosk
        command: bash -c "apt-get update && apt-get install -y libportaudio2 portaudio19-dev ffmpeg && pip install --no-cache-dir -r requirements.txt && gunicorn -w 4 -b 0.0.0.0:3800 app:app"
        ports:
            - 3800:3800
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
            - type: bind
              source: ../audio
              target: /srv/app/audio
        tty: true
